# Generated by Django 3.1.3 on 2021-01-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sample',
            field=models.TextField(default=0.0, max_length=150),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
